name: "Bug报告"
description: "报告PyLamina的Bug"
labels: [new report, bug]
body:
- type: checkboxes
  id: "yml-1"
  attributes:
    label: "检查项"
    description: "检查是否是PyLamina的错误，而非其他原因。"
    options:
    - label: "我在最新版本的PyLamina尝试运行，但仍出现错误"
      required: true
    - label: "我在Issues中搜索并确认了没有重复其他Issue"
      required: true
    - label: "我仔细阅读了检查项，知道了这个选项不用勾选"
      required: false
    - label: "我已经尝试过在Lamina中运行，Lamina没有出错而PyLamina出现错误"
      required: true
- type: textarea
  id: "yml-2"
  attributes:
    label: 原因
    description: "描述你如何触发Bug"
  validations:
    required: true
- type: textarea
  id: "yml-3"
  attributes:
    label: 现象
    description: "PyLamina出现了什么错误"
  validations:
    required: true
- type: textarea
  id: "yml-4"
  attributes:
    label: 期望
    description: "你期望PyLamina作出的正确行为"
  validations:
    required: true
- type: textarea
  id: "yml-5"
  attributes:
    label: 环境
    description: "你的电脑的彻底情况（如Windows11专业工作站版24H2）"
  validations:
    required: false
- type: textarea
  id: "yml-6"
  attributes:
    label: 附件
    description: "在这里上传日志/TraceBack等信息"
  validations:
    required: false